### ISSUE TITLE
Balancing seems off on some modules

### ISSUE THREAD

**Issue by anikrooz** [tomdebree/VW-bms#1]
Have to say to start off this project has been a lifesaver!

Balancing is working well on many modules, but several seem to keep a bunch of cells 0.1v higher than the rest - no matter how long balancing goes on for. To illustrate, here's my current cell voltages. They've discharged a bit since balancing - but at the end of balancing the 0.1v difference is even more exact:
`{
	"A7": {
		"cells": [3.52, 3.52, 3.52, 3.52, 3.52, 3.52, 3.52, 3.53, 3.53, 3.53, 3.53, 3.53]
	},

	"A8": {
		"cells": [3.52, 3.52, 3.52, 3.52, 3.52, 3.52, 3.52, 3.52, 3.53, 3.53, 3.53, 3.53]
	},

	"B1": {
		"cells": [3.48, 3.48, 3.48, 3.48, 3.49, 3.49, 3.49, 3.58, 3.58, 3.58, 3.57, 3.58]
	},

	"B2": {
		"cells": [3.50, 3.49, 3.49, 3.49, 3.50, 3.50, 3.50, 3.58, 3.57, 3.57, 3.57, 3.58]
	},

	"B4": {
		"cells": [3.48, 3.48, 3.48, 3.48, 3.49, 3.49, 3.49, 3.59, 3.58, 3.58, 3.58, 3.56]
	},

	"B6": {
		"cells": [3.48, 3.48, 3.48, 3.48, 3.48, 3.48, 3.48, 3.58, 3.58, 3.58, 3.57, 3.58]
	},

	"B7": {
		"cells": [3.48, 3.48, 3.47, 3.47, 3.47, 3.47, 3.47, 3.59, 3.59, 3.59, 3.58, 3.59]
	}
}`

There are two CAN buses here; I'm using modified code to initiate 2 bms instances.
You can see a split between cells 0-6 and 7-11 on all but the first 2 modules. I don't quite understand the balancing code, but is it possible it's stlling some cells to balance higher than others? 
Any pointers as to what the bits in the balancing CAN messages mean would be appreciated. Happy to help debug

**Comment by Tom-evnut** [comment]
But this is only on the second "modified" canbus?

**Comment by anikrooz** [comment]
Sorry I meant to update this... I'd left in the balancingTest function, which was messing with a couple of modules and breaking balancing on the rest!
All seems okay now, with the modified module 3 addresses as per #2
